### ISSUE TITLE
APISpecError: Path template is not specified.

### ISSUE THREAD

**Issue by Denis-Alexeev** [ovh/python-apispec-fromfile#3]
When I try exact example from ReadME - I get:

```
Traceback (most recent call last):
  File ".../app.py", line 29, in <module>
    spec.path(resource=hello)
  File ".../venv/lib/python3.9/site-packages/apispec/core.py", line 295, in path
    raise APISpecError("Path template is not specified.")
apispec.exceptions.APISpecError: Path template is not specified.
```

What am I doing wrong?

**Comment by Linkid** [comment]
Hi !
Thank you for reporting this issue :).

I actually forgot to specify the endpoint and did like I was using the `FlaskPlugin` plugin :cyclone:. I'll fix it and add a test.
Here what you should do: `spec.path("/hello", resource=hello)`.

Thanks again.
